package lt.vu.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;

import lt.vu.mybatis.model.DishOrder;

@Mapper
public interface DishOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH_ORDER
     *
     * @mbg.generated Fri Apr 29 22:07:59 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH_ORDER
     *
     * @mbg.generated Fri Apr 29 22:07:59 EEST 2022
     */
    int insert(DishOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH_ORDER
     *
     * @mbg.generated Fri Apr 29 22:07:59 EEST 2022
     */
    DishOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH_ORDER
     *
     * @mbg.generated Fri Apr 29 22:07:59 EEST 2022
     */
    List<DishOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH_ORDER
     *
     * @mbg.generated Fri Apr 29 22:07:59 EEST 2022
     */
    int updateByPrimaryKey(DishOrder record);
}