package lt.vu.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;

import lt.vu.mybatis.model.Dish;

@Mapper
public interface DishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    int insert(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    Dish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    List<Dish> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISH
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    int updateByPrimaryKey(Dish record);
}