package lt.vu.mybatis.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.FIRST_NAME
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.LAST_NAME
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.FIRST_NAME
     *
     * @return the value of PUBLIC.CUSTOMER.FIRST_NAME
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.CUSTOMER.FIRST_NAME
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.LAST_NAME
     *
     * @return the value of PUBLIC.CUSTOMER.LAST_NAME
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.CUSTOMER.LAST_NAME
     *
     * @mbg.generated Fri Apr 29 22:06:02 EEST 2022
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}