package lt.vu.mybatis.model;

public class Dish {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISH.ID
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISH.DESCRIPTION
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISH.NAME
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISH.PRICE
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISH.ID
     *
     * @return the value of PUBLIC.DISH.ID
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISH.ID
     *
     * @param id the value for PUBLIC.DISH.ID
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISH.DESCRIPTION
     *
     * @return the value of PUBLIC.DISH.DESCRIPTION
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISH.DESCRIPTION
     *
     * @param description the value for PUBLIC.DISH.DESCRIPTION
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISH.NAME
     *
     * @return the value of PUBLIC.DISH.NAME
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISH.NAME
     *
     * @param name the value for PUBLIC.DISH.NAME
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISH.PRICE
     *
     * @return the value of PUBLIC.DISH.PRICE
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISH.PRICE
     *
     * @param price the value for PUBLIC.DISH.PRICE
     *
     * @mbg.generated Fri Apr 29 22:06:01 EEST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}