package lt.vu.mybatis.model;

import java.util.Date;

public class DishOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISH_ORDER.ID
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISH_ORDER.DATE
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISH_ORDER.CUSTOMER_ID
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISH_ORDER.ID
     *
     * @return the value of PUBLIC.DISH_ORDER.ID
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISH_ORDER.ID
     *
     * @param id the value for PUBLIC.DISH_ORDER.ID
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISH_ORDER.DATE
     *
     * @return the value of PUBLIC.DISH_ORDER.DATE
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISH_ORDER.DATE
     *
     * @param date the value for PUBLIC.DISH_ORDER.DATE
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISH_ORDER.CUSTOMER_ID
     *
     * @return the value of PUBLIC.DISH_ORDER.CUSTOMER_ID
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISH_ORDER.CUSTOMER_ID
     *
     * @param customerId the value for PUBLIC.DISH_ORDER.CUSTOMER_ID
     *
     * @mbg.generated Sat Apr 30 22:38:38 EEST 2022
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}